/* This file is automatically generated. Do not edit. */
.section __TEXT,__objc_selopt
.private_extern __objc_selopt_data
__objc_selopt_data:
.long  3 /* table.version */
.long 4 /* table.capacity */
.long 4 /* table.occupied */
.long 63 /* table.shift */
.long 3 /* table.mask */
.long 0 /* table.zero */
.quad 0 /* table.salt */
.quad  0 /* table.base */
.space 256*4 /* table.scramble */
.long 0  /* table.tab */
.long 20 /* table.offsets */
.long 20
.long 20
.long 20
/* space for smax/capacity=131072, blen/mask=65535+1 */
.space 65536
.space 131072*4
