/* This file is automatically generated. Do not edit. */
.section __TEXT,__objc_opt_ro
.align 3
.private_extern __objc_opt_data
__objc_opt_data:
.long 10 /* table.version */
.long 0 /* table.selopt_offset */
.space 4096-8

/* space for selopt, smax/capacity=131072, blen/mask=65535+1 */
.space 65536
.space 131072*4  /* offsets */
.space 131072    /* checkbytes */

#if __arm__
.section __DATA,__objc_opt_rw
.align 3
.space 256*1024
#else
/* optimization performed in linker, not shared cache */
#endif
